apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: local-kafka-kubernetes
nodes:
- role: control-plane
# ArgoCD 
  extraPortMappings:
  - containerPort: 30080 
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker
# control-center
  extraPortMappings:
  - containerPort: 30021
    hostPort: 30021
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker
- role: worker